# Generated by Django 4.2.5 on 2023-09-05 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0002_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='espense',
            new_name='expense',
        ),
    ]
