# Generated by Django 4.2.5 on 2023-09-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0003_rename_espense_transaction_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesdb',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
